### PR TITLE
Close the process when shutdown is finished

### PR DESCRIPTION
**Pull request by supermario1990**
optimized StartServer function when shutdown

### CODE REVIEW

**Comment by kevwan** [comment]
it's not necessary, because there is control logic in core/proc/shutdown.go

at most, the process will wait for 5.5 seconds, if the cleanup finished fast, the callback is called, otherwise, the process is forced to quit.

**Comment by supermario1990** [comment]
可能我的描述并没有表达清楚PR的意义。
目前存在的问题：
rest server 并不能做到优雅关闭。这点我自己验证过。目前的代码是这样的(rest/internal/starter.go）
```
func StartServer(srv *http.Server) error {
	proc.AddWrapUpListener(func() {
		srv.Shutdown(context.Background())
	})

	return srv.ListenAndServe()
}
```
整个进程阻塞在 `return srv.ListenAndServe()`这句话， 当`Shutdown`被调用时，`srv.ListenAndServe()` 立刻会返回`ErrServerClosed`, 然后进程就退出了。这时候可能还有请求没有处理完。优雅关闭必须要等`Shutdown`处理完才结束进程。

**Comment by supermario1990** [comment]
稍后补个例子吧

**Comment by supermario1990** [comment]
> 稍后补个例子吧

https://github.com/supermario1990/shorturl

**Pull request merged**
