### PR TITLE
add etcd subscriber returns map

### PR DESCRIPTION
**Pull request by woodylan**
We need to monitor every key/value change, not just value

### CODE REVIEW

**Comment by kevwan** [comment]
please describe why we need to return map, thanks!

**Comment by woodylan** [comment]
需要监听每个值的key/value变化，利用values()方法只能显示value，没有key

**Comment by kevwan** [comment]
每个key只是给定的前缀再加了个随机string

**Comment by kevwan** [comment]
暂不接受这个PR哈 :P

**Pull request closed without merging**
