### PR TITLE
chore: update code format.

### PR DESCRIPTION
**Pull request by appleboy**
as title.

### CODE REVIEW

**Comment by kevwan** [comment]
changed by any tool or manually? :P

**Comment by appleboy** [comment]
@kevwan https://github.com/mvdan/gofumpt maybe add to check list?

**Comment by kevwan** [comment]
> @kevwan https://github.com/mvdan/gofumpt maybe add to check list and add `_mock.go` to ignore list?

thank you! I'll check if can I add it to CI.

**Comment by tiptok** [comment]
can it be used like this ?  
``` go
defaultDirMode  = 0o755  // rotatelogger.go

err := os.MkdirAll(dir, 0o755)    //change from '0755' to  '0o755'
```

**Pull request merged**
